//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Автоматизация.
    /// </summary>
    // *** Start programmer edit section *** (Автоматизация CustomAttributes)

    // *** End programmer edit section *** (Автоматизация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Автоматизация : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Kursovaya7.DetailArrayOfПокупка fПокупка;
        
        // *** Start programmer edit section *** (Автоматизация CustomMembers)

        // *** End programmer edit section *** (Автоматизация CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Автоматизация.Номер CustomAttributes)

        // *** End programmer edit section *** (Автоматизация.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Автоматизация.Номер Get start)

                // *** End programmer edit section *** (Автоматизация.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Автоматизация.Номер Get end)

                // *** End programmer edit section *** (Автоматизация.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автоматизация.Номер Set start)

                // *** End programmer edit section *** (Автоматизация.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Автоматизация.Номер Set end)

                // *** End programmer edit section *** (Автоматизация.Номер Set end)
            }
        }
        
        /// <summary>
        /// Автоматизация.
        /// </summary>
        // *** Start programmer edit section *** (Автоматизация.Покупка CustomAttributes)

        // *** End programmer edit section *** (Автоматизация.Покупка CustomAttributes)
        public virtual IIS.Kursovaya7.DetailArrayOfПокупка Покупка
        {
            get
            {
                // *** Start programmer edit section *** (Автоматизация.Покупка Get start)

                // *** End programmer edit section *** (Автоматизация.Покупка Get start)
                if ((this.fПокупка == null))
                {
                    this.fПокупка = new IIS.Kursovaya7.DetailArrayOfПокупка(this);
                }
                IIS.Kursovaya7.DetailArrayOfПокупка result = this.fПокупка;
                // *** Start programmer edit section *** (Автоматизация.Покупка Get end)

                // *** End programmer edit section *** (Автоматизация.Покупка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автоматизация.Покупка Set start)

                // *** End programmer edit section *** (Автоматизация.Покупка Set start)
                this.fПокупка = value;
                // *** Start programmer edit section *** (Автоматизация.Покупка Set end)

                // *** End programmer edit section *** (Автоматизация.Покупка Set end)
            }
        }
    }
}
